"""Loop tests on a throwaway git repo; radar and LLM are stubbed (no network)."""

import json
import os
import shutil
import subprocess
from pathlib import Path

import yaml

from noirstudio import loop, radar as radar_mod

ROOT = Path(__file__).resolve().parents[3]
GIT_ENV = {**os.environ, "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@t", "GIT_COMMITTER_NAME": "t",
           "GIT_COMMITTER_EMAIL": "t@t"}


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True, text=True, env=GIT_ENV).stdout


def _make_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    (repo / "specs").mkdir(parents=True)
    shutil.copy(ROOT / "specs" / "agent-log-001.yaml", repo / "specs" / "agent-log-001.yaml")
    (repo / "radar.yaml").write_text(radar_mod.DEFAULT_CONFIG, encoding="utf-8")
    (repo / ".gitignore").write_text("renders/\n", encoding="utf-8")
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "init")
    return repo


def test_next_entry(tmp_path):
    d = tmp_path / "specs"
    d.mkdir()
    assert loop.next_entry(d) == "001"
    (d / "agent-log-001.yaml").write_text("x")
    (d / "agent-log-003.yaml").write_text("x")
    (d / "other.yaml").write_text("x")
    assert loop.next_entry(d) == "004"


def test_headlines_evidence_sorts_and_dedups(tmp_path):
    snap = {"generated_at": "2026-09-28T10:00:00+00:00", "stories": [
        {"id": "1", "title": "low", "url": "u1", "points": 5, "comments": 0, "created_at": "c", "pph": 1, "query": "q"},
        {"id": "2", "title": "high", "url": "u2", "points": 359, "comments": 251, "created_at": "c", "pph": 2, "query": "q"},
        {"id": "2", "title": "high", "url": "u2", "points": 359, "comments": 251, "created_at": "c", "pph": 2, "query": "q2"},
    ]}
    p = tmp_path / "snap.json"
    p.write_text(json.dumps(snap))
    out = tmp_path / "ev" / "hn.json"
    assert loop.headlines_evidence(p, out, n=10) == 2
    rows = json.loads(out.read_text())["stories"]
    assert [r["title"] for r in rows] == ["high", "low"] and rows[0]["points"] == 359


def test_run_agent_log_materials_only(tmp_path, monkeypatch):
    repo = _make_repo(tmp_path)

    def fake_radar_run(config_path, out_dir, **kw):
        (out_dir / "briefs").mkdir(parents=True, exist_ok=True)
        (out_dir / "snapshots").mkdir(parents=True, exist_ok=True)
        date = loop.datetime.now(loop.timezone.utc).strftime("%Y-%m-%d")
        (out_dir / "snapshots" / f"{date}.json").write_text(json.dumps({"generated_at": "x", "stories": [
            {"id": "9", "title": "Show HN: thing", "url": "u", "points": 42, "comments": 3, "created_at": "c", "pph": 1, "query": "q"}]}))
        brief = out_dir / "briefs" / f"{date}.md"
        brief.write_text("# Radar brief\n\n| 1 | 42 | 3 | Show HN: thing |\n")
        return brief

    monkeypatch.setattr(radar_mod, "run", fake_radar_run)
    for k in ("OPENROUTER_API_KEY", "DEEPSEEK_API_KEY", "YOUTUBE_API_KEY"):
        monkeypatch.delenv(k, raising=False)

    res = loop.run_agent_log(repo, draft="auto", push=False, pr=False, log=lambda _m: None)
    assert res.entry == "002" and res.branch == "agent-log/002"
    assert res.steps["radar"].startswith("ok") and res.steps["activity"] == "ok"
    assert res.steps["headlines"] == "1 saved"
    assert res.steps["draft"].startswith("skipped") and res.spec_path is None
    assert res.steps["commit"] == "ok" and "push" not in res.steps
    assert _git(repo, "rev-parse", "--abbrev-ref", "HEAD").strip() == "agent-log/002"
    committed = _git(repo, "show", "--name-only", "--format=", "HEAD").split()
    assert any(f.startswith("specs/evidence/") and f.endswith("-activity.json") for f in committed)
    assert any(f.endswith("-hn-top.json") for f in committed)
    assert any(f.startswith("radar/briefs/") for f in committed)
    body = loop.pr_body(res, repo)
    assert "No spec was drafted" in body and "Show HN: thing" in body and "_Generated by" in body


def test_run_agent_log_with_stub_drafter_renders_and_commits_spec(tmp_path, monkeypatch):
    repo = _make_repo(tmp_path)
    date = loop.datetime.now(loop.timezone.utc).strftime("%Y-%m-%d")

    def fake_radar_run(config_path, out_dir, **kw):
        (out_dir / "briefs").mkdir(parents=True, exist_ok=True)
        (out_dir / "snapshots").mkdir(parents=True, exist_ok=True)
        (out_dir / "snapshots" / f"{date}.json").write_text(json.dumps({"generated_at": "x", "stories": []}))
        brief = out_dir / "briefs" / f"{date}.md"
        brief.write_text("# Radar brief\n")
        return brief

    monkeypatch.setattr(radar_mod, "run", fake_radar_run)
    monkeypatch.delenv("OPENROUTER_API_KEY", raising=False)
    monkeypatch.setenv("DEEPSEEK_API_KEY", "fake")

    from noirstudio import draft as draft_mod

    def fake_draft(client, *, entry, out_path, **kw):
        data = yaml.safe_load((ROOT / "specs" / "agent-log-001.yaml").read_text(encoding="utf-8"))
        data["id"] = f"agent-log-{entry}"
        data["brand_overrides"]["wordmark"] = f"AGENT LOG · {entry}"
        data["scenes"][-1]["text"] = f"Entry {entry}. Tomorrow I'll tell you what I did. He'll tell you whether it mattered."
        data["output"] = {"width": 540, "height": 960, "fps": 24}
        out_path.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True), encoding="utf-8")
        from noirstudio.spec import load_spec
        return draft_mod.DraftResult(load_spec(out_path), out_path, 1, data)

    monkeypatch.setattr(draft_mod, "draft_agent_log", fake_draft)

    res = loop.run_agent_log(repo, draft="auto", push=False, pr=False, log=lambda _m: None)
    assert res.steps["draft"] == "ok" and res.drafter.startswith("deepseek/")
    assert res.spec_path == "specs/agent-log-002.yaml"
    assert res.steps["render"].startswith("ok") and (repo / "renders" / "agent-log-002" / "agent-log-002.mp4").exists()
    committed = _git(repo, "show", "--name-only", "--format=", "HEAD").split()
    assert "specs/agent-log-002.yaml" in committed and not any(f.startswith("renders/") for f in committed)
    assert _git(repo, "log", "-1", "--format=%s").startswith("Agent Log 002: ")
    body = loop.pr_body(res, repo)
    assert "### Narration" in body and "### Upload metadata" in body


def test_rerun_reuses_remote_branch(tmp_path, monkeypatch):
    """Second run of the same day must stack on the pushed branch, not fail the push."""
    origin = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(origin)], check=True)
    repo = _make_repo(tmp_path)
    _git(repo, "remote", "add", "origin", str(origin))
    _git(repo, "push", "-q", "-u", "origin", "main")
    _git(repo, "remote", "set-head", "origin", "main")

    def fake_radar_run(config_path, out_dir, **kw):
        (out_dir / "briefs").mkdir(parents=True, exist_ok=True)
        (out_dir / "snapshots").mkdir(parents=True, exist_ok=True)
        date = loop.datetime.now(loop.timezone.utc).strftime("%Y-%m-%d")
        (out_dir / "snapshots" / f"{date}.json").write_text(json.dumps({"generated_at": "x", "stories": []}))
        brief = out_dir / "briefs" / f"{date}.md"
        brief.write_text(f"# Radar brief {loop.datetime.now(loop.timezone.utc).isoformat()}\n")
        return brief

    monkeypatch.setattr(radar_mod, "run", fake_radar_run)
    for k in ("OPENROUTER_API_KEY", "DEEPSEEK_API_KEY", "YOUTUBE_API_KEY"):
        monkeypatch.delenv(k, raising=False)

    first = loop.run_agent_log(repo, draft="skip", push=True, pr=False, log=lambda _m: None)
    assert first.steps["branch"] == "ok" and first.steps["push"] == "ok"
    _git(repo, "checkout", "-q", "main")
    (repo / "later.txt").write_text("x")  # the base moves on while the entry's PR is open
    _git(repo, "add", "later.txt")
    _git(repo, "commit", "-q", "-m", "later on main")
    _git(repo, "push", "-q", "origin", "main")
    second = loop.run_agent_log(repo, draft="skip", push=True, pr=False, log=lambda _m: None)
    assert second.entry == first.entry and second.steps["branch"] == "reused remote"
    assert second.steps["push"] == "ok"
    log = _git(repo, "log", "--oneline", f"origin/{first.branch}")
    assert log.count("\n") >= 3  # init + two loop commits
    assert "later on main" in log  # base merged in, so the drafter and history are today's
    activity = json.loads((repo / next(f for f in second.files if f.endswith("-activity.json"))).read_text())
    authored = [(c["author"], c["subject"]) for c in activity["repos"][0]["commits"]]
    assert ("t", "later on main") in authored and not any(a == "noirstudio" for a, _ in authored)


def test_default_branch_keeps_slashes(tmp_path):
    repo = _make_repo(tmp_path)
    _git(repo, "update-ref", "refs/remotes/origin/claude/x", "HEAD")
    _git(repo, "symbolic-ref", "refs/remotes/origin/HEAD", "refs/remotes/origin/claude/x")
    assert loop.default_branch(repo) == "claude/x"
