"""The Agent Log loop as one command, so any runner can execute it:

    noirstudio loop agent-log [--draft auto|skip] [--push] [--pr] [--notes ...]

Steps: next entry number -> radar -> activity -> verbatim headline evidence ->
draft (LLM if a key exists, else a "materials only" PR) -> validate -> offline
render -> commit -> push -> open PR (gh, or the REST API with GH_TOKEN).
Every step reports into a summary the caller prints as JSON. Nothing publishes.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from . import radar as radar_mod
from .activity import collect
from .spec import load_spec

ENTRY_RE = re.compile(r"agent-log-(\d{3})\.yaml$")


@dataclass
class LoopResult:
    entry: str
    branch: str
    date: str
    steps: Dict[str, str] = field(default_factory=dict)
    files: List[str] = field(default_factory=list)
    spec_path: Optional[str] = None
    render_dir: Optional[str] = None
    pr_url: Optional[str] = None
    drafter: str = "none"
    errors: List[str] = field(default_factory=list)

    def to_json(self) -> str:
        return json.dumps(self.__dict__, indent=2)


def _run(cmd: List[str], cwd: Path, check: bool = True, env: Optional[dict] = None) -> subprocess.CompletedProcess:
    proc = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, env=env)
    if check and proc.returncode != 0:
        raise RuntimeError(f"{' '.join(cmd)} failed ({proc.returncode}): {proc.stderr.strip()[-800:]}")
    return proc


def next_entry(specs_dir: Path) -> str:
    nums = [int(m.group(1)) for p in specs_dir.glob("agent-log-*.yaml") if (m := ENTRY_RE.search(p.name))]
    return f"{(max(nums) + 1) if nums else 1:03d}"


def default_branch(repo: Path) -> str:
    proc = _run(["git", "symbolic-ref", "refs/remotes/origin/HEAD"], repo, check=False)
    if proc.returncode == 0 and proc.stdout.strip():
        return proc.stdout.strip().rsplit("/", 1)[-1]
    proc = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"], repo)
    return proc.stdout.strip()


def headlines_evidence(snapshot_path: Path, out_path: Path, n: int = 10) -> int:
    """Copy the top-n HN stories verbatim from a radar snapshot into an evidence file."""
    snap = json.loads(snapshot_path.read_text(encoding="utf-8"))
    stories = sorted(snap.get("stories", []), key=lambda s: -int(s.get("points", 0)))
    seen, rows = set(), []
    for s in stories:
        if s["id"] in seen:
            continue
        seen.add(s["id"])
        rows.append({k: s.get(k) for k in ("id", "title", "url", "points", "comments", "created_at", "pph", "query")})
        if len(rows) >= n:
            break
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps({"source": "Hacker News via Algolia API", "collected_at": snap.get("generated_at"),
                                    "stories": rows}, indent=2), encoding="utf-8")
    return len(rows)


def pr_body(result: LoopResult, repo: Path) -> str:
    lines = [f"## Agent Log · Entry {result.entry}", ""]
    if result.spec_path:
        spec = load_spec(repo / result.spec_path)
        lines += ["### Narration", ""]
        for i, s in enumerate(spec.scenes, 1):
            lines.append(f"{i}. {s.text.strip()}")
        lines.append("")
        meta = Path(result.render_dir or "") / f"{spec.id}.metadata.md" if result.render_dir else None
        if meta and (repo / meta).exists():
            lines += ["### Upload metadata", "", (repo / meta).read_text(encoding="utf-8"), ""]
    else:
        lines += ["No spec was drafted (no LLM key in this runner). Evidence and the radar brief are attached; ",
                  "a person or a Claude session drafts the entry from them.", ""]
    lines += ["### Evidence", ""] + [f"- `{f}`" for f in result.files if "evidence" in f or "radar/" in f] + [""]
    brief = repo / "radar" / "briefs" / f"{result.date}.md"
    if brief.exists():
        head = [l for l in brief.read_text(encoding="utf-8").splitlines() if l.strip()][:8]
        lines += ["### Radar (top of today's brief)", "", *head, ""]
    lines += [f"Drafter: {result.drafter}. Steps: " + ", ".join(f"{k}={v}" for k, v in result.steps.items()), ""]
    if result.errors:
        lines += ["### Blocked / fallbacks", ""] + [f"- {e}" for e in result.errors] + [""]
    lines += ["---", "_Generated by [Claude Code](https://claude.ai/code)_"]
    return "\n".join(lines)


def _github_repo(repo: Path) -> tuple:
    remote = _run(["git", "remote", "get-url", "origin"], repo).stdout.strip()
    m = re.search(r"github\.com[:/]([^/]+)/([^/.]+)", remote)
    if not m:
        raise RuntimeError(f"cannot parse GitHub remote: {remote}")
    return m.group(1), m.group(2)


def _api(method: str, url: str, token: str, payload: Optional[dict] = None) -> dict:
    req = urllib.request.Request(url, data=json.dumps(payload).encode() if payload is not None else None, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github+json")
    if payload is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode(errors="replace")[:300]
        hint = ""
        if exc.code == 403 and "pull request" in detail.lower():
            hint = " — enable Settings > Actions > General > 'Allow GitHub Actions to create and approve pull requests'"
        raise RuntimeError(f"GitHub API {method} {url.split('/repos/')[-1]} -> HTTP {exc.code}: {detail}{hint}") from None


def open_pr(repo: Path, head: str, base: str, title: str, body: str, reviewer: str = "vzbb") -> str:
    """Open (or update) the PR for `head`. Prefers gh; falls back to the REST API with GH_TOKEN."""
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    owner, name = _github_repo(repo)
    api = f"https://api.github.com/repos/{owner}/{name}"

    # an earlier run today may already have opened the PR: update it instead of failing
    if token:
        existing = _api("GET", f"{api}/pulls?state=open&head={owner}:{urllib.parse.quote(head, safe='')}", token)
        if existing:
            pr = existing[0]
            _api("PATCH", f"{api}/pulls/{pr['number']}", token, {"title": title, "body": body})
            return pr["html_url"]

    err = "gh not installed"
    if shutil.which("gh"):
        body_file = repo / "renders" / "PR_BODY.md"
        body_file.parent.mkdir(exist_ok=True)
        body_file.write_text(body, encoding="utf-8")
        proc = _run(["gh", "pr", "create", "--title", title, "--body-file", str(body_file), "--base", base, "--head", head],
                    repo, check=False)
        if proc.returncode == 0:
            url = proc.stdout.strip().splitlines()[-1]
            _run(["gh", "pr", "edit", url, "--add-reviewer", reviewer], repo, check=False)
            return url
        err = proc.stderr.strip()[-400:]
    if not token:
        raise RuntimeError(f"cannot open PR: {err}; and no GH_TOKEN/GITHUB_TOKEN for the REST API")
    pr = _api("POST", f"{api}/pulls", token, {"title": title, "head": head, "base": base, "body": body})
    try:
        _api("POST", f"{api}/pulls/{pr['number']}/requested_reviewers", token, {"reviewers": [reviewer]})
    except Exception:  # reviewer request is best-effort
        pass
    return pr["html_url"]


def run_agent_log(repo: Path, *, draft: str = "auto", push: bool = False, pr: bool = False, notes: str = "",
                  use_youtube: Optional[bool] = None, git_user: str = "noirstudio", git_email: str = "noirstudio@noirsys.com",
                  radar_config: str = "radar.yaml", log=print) -> LoopResult:
    repo = repo.resolve()
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    entry = next_entry(repo / "specs")
    base = default_branch(repo)
    branch = f"agent-log/{entry}"
    res = LoopResult(entry=entry, branch=branch, date=date)
    log(f"[loop] entry {entry} on {branch} (base {base}), {date}")

    # branch — reuse today's remote branch if a previous run already pushed it, so re-runs
    # stack on it (and update the same PR) instead of failing the push
    remote_exists = _run(["git", "ls-remote", "--exit-code", "--heads", "origin", branch], repo, check=False).returncode == 0
    if remote_exists:
        _run(["git", "fetch", "origin", branch], repo)
        _run(["git", "checkout", "-B", branch, f"origin/{branch}"], repo)
        res.steps["branch"] = "reused remote"
    else:
        _run(["git", "checkout", "-B", branch], repo)
        res.steps["branch"] = "ok"

    # radar
    if use_youtube is None:
        use_youtube = bool(os.environ.get(radar_mod.ENV_YT_KEY))
    try:
        brief_path = radar_mod.run(repo / radar_config, repo / "radar", use_youtube=use_youtube, use_hn=True)
        res.files += [str(brief_path.relative_to(repo)), f"radar/snapshots/{date}.json"]
        res.steps["radar"] = f"ok (youtube={'on' if use_youtube else 'off'})"
    except Exception as exc:
        res.errors.append(f"radar: {exc}")
        res.steps["radar"] = "failed"
        brief_path = None

    # activity
    activity_path = repo / "specs" / "evidence" / f"{date}-activity.json"
    activity_path.parent.mkdir(parents=True, exist_ok=True)
    activity_path.write_text(json.dumps(collect([repo], since="1.day", render_roots=[repo / "renders"]), indent=2),
                             encoding="utf-8")
    res.files.append(str(activity_path.relative_to(repo)))
    res.steps["activity"] = "ok"

    # headlines (verbatim)
    headlines_path = None
    snap = repo / "radar" / "snapshots" / f"{date}.json"
    if snap.exists():
        headlines_path = repo / "specs" / "evidence" / f"{date}-hn-top.json"
        n = headlines_evidence(snap, headlines_path)
        res.files.append(str(headlines_path.relative_to(repo)))
        res.steps["headlines"] = f"{n} saved"

    # draft
    spec_path = repo / "specs" / f"agent-log-{entry}.yaml"
    if draft != "skip":
        from .llm import LLMError, resolve_client

        try:
            client = resolve_client()
            from .draft import DraftError, draft_agent_log

            prev = repo / "specs" / f"agent-log-{int(entry) - 1:03d}.yaml"
            r = draft_agent_log(client, entry=entry, activity_path=activity_path, brief_path=brief_path,
                                headlines_path=headlines_path, previous_spec=prev if prev.exists() else None,
                                out_path=spec_path, notes=notes)
            res.drafter = f"{client.provider}/{client.model} (attempt {r.attempts})"
            res.spec_path = str(spec_path.relative_to(repo))
            res.files.append(res.spec_path)
            res.steps["draft"] = "ok"
        except LLMError as exc:
            res.steps["draft"] = "skipped (no LLM key)"
            res.errors.append(f"draft skipped: {exc}")
        except DraftError as exc:
            res.steps["draft"] = "rejected"
            res.errors.append(f"draft rejected: {exc}")
    else:
        res.steps["draft"] = "skipped"

    # render (offline)
    if res.spec_path:
        from .pipeline import render

        out_dir = repo / "renders" / f"agent-log-{entry}"
        try:
            rr = render(spec_path, out_dir, live=False, keep_work=False, log=lambda _m: None)
            res.render_dir = str(out_dir.relative_to(repo))
            fb = [f"{s.id}: {s.fallback}" for s in rr.scenes if s.fallback]
            res.steps["render"] = f"ok ({rr.duration:.1f}s)" + (f" fallbacks: {'; '.join(fb)}" if fb else "")
        except Exception as exc:
            res.steps["render"] = "failed"
            res.errors.append(f"render: {exc}")

    # commit
    _run(["git", "config", "user.name", git_user], repo)
    _run(["git", "config", "user.email", git_email], repo)
    _run(["git", "add", "--", *res.files], repo)
    title = f"Agent Log {entry}: " + (load_spec(spec_path).publish.title or load_spec(spec_path).title if res.spec_path
                                      else f"materials for {date} (no draft)")
    if _run(["git", "diff", "--cached", "--quiet"], repo, check=False).returncode == 0:
        res.steps["commit"] = "nothing to commit"
        return res
    _run(["git", "commit", "-q", "-m", title], repo)
    res.steps["commit"] = "ok"

    if push:
        _run(["git", "push", "-u", "origin", branch, "--force-with-lease"], repo)
        res.steps["push"] = "ok"
    if pr and push:
        try:
            res.pr_url = open_pr(repo, branch, base, title[:200], pr_body(res, repo))
            res.steps["pr"] = "ok"
        except Exception as exc:
            res.steps["pr"] = "failed"
            res.errors.append(f"pr: {exc}")
            (repo / "renders").mkdir(exist_ok=True)
            (repo / "renders" / "PR_BODY.md").write_text(pr_body(res, repo), encoding="utf-8")
    return res
